# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: MPW技术博客
subtitle: ""
description: ""
keywords:
author: zhixuan li
language: zh
timezone: ""

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://myprototypewhat.github.io
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ""
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
syntax_highlighter: prismjs
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ""
  wrap: true
  hljs: false
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ""
prism_plugin:
  mode: "preprocess" # realtime/preprocess
  theme: "default"

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ""
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: "mtime"

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: gstyle

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: ""

auto-issue:
  owner: myprototypewhat # github拥有者 
  repo: take-down_react # 仓库名
  auth: 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 # github token
  userAgent: hexo-auto-iissue # 自定义请求头
  sort_by: date # 文章排序 可选data|updated 默认t: data
  withGitalk: true # 如果为true, 将自动生成一个gitalkId的label, 默认: false
  delay: 2000 # 每次发布的延迟时间,防止被判定为机器人 默认: 2000毫秒
  template:
    title: {{title}} - myprototypewhat's blog  # issue 标题模板 默认: {{title}}
    body: |- # issue 内容模板. 默认: {{ _content }}
      {{title}}
      {{_content}}
      blog link [{{title}}](https://myprototypewhat.github.io)
    labels: |- # issue 标签模板. 默认: {{ tags.data|join(',', 'name') }},{{ categories.data|join(',', 'name') }}
      {{ tags.data|join(',', 'name') }},{{ categories.data|join(',', 'name') }}