name: Hexo SEO Auto Push

on:
  push:
    branches:
      - master # default branch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@main
        with:
          node-version: latest
      - name: Set Environment Variable
        run: echo "PUBLIC_PATH=./public" >> $GITHUB_ENV
      # - name: google push
      #   run: npm run hexoautopush ${{secrets.google_client_email}} ${{secrets.google_private_key}}

      - name: bing push
        run: curl -X POST "https://ssl.bing.com/webmaster/api.svc/json/SubmitUrlBatch?apikey=${{secrets.bing_apikey}}" -H "Content-Type:application/json" -H "charset:utf-8" -d @${{PUBLIC_PATH}}/bing.json

      - name: baidu push
        run: curl -H "Content-Type:text/plain" --data-binary @@${{PUBLIC_PATH}}/baidu.txt "http://data.zz.baidu.com/urls?site=https://myprototypewhat.github.io&token=${{secrets.baidu_token}}"
